version: '3'

tasks:

  ##############################################
  # Module support
  ##############################################
  update:
    desc: Update the project dependencies
    cmds:
      - echo "Updating dependencies..."
      - go get -u ./...
      - go mod tidy
      - echo "Dependencies updated"
    silent: true

  ##############################################
  # App support
  ##############################################
  server:
    desc: Run the Go server
    deps:
      - proto
    cmds:
      - echo "Starting the server..."
      - go run ./cmd/grpcapi/server.go
      - echo "Server started successfully"  
    silent: true

  ##############################################
  # Clean up proto gen files
  ##############################################
  clean:
    desc: Clean up the proto generation files
    cmds:
      - rm -rf ./proto/gen
      - echo "Proto generation files cleaned up" 
    silent: true

  ##############################################
  # Generate proto files
  ##############################################
  proto:
    desc: Generate Go code from Protobuf files
    cmds:
      - protoc -I=proto --go_out=. --go-grpc_out=. proto/*.proto
      - echo "Protobuf files generated"
    silent: true

  ##############################################
  # Compose up
  ##############################################
  compose:
    desc: Run a Docker Compose command
    cmds:
      - docker compose up -d --force-recreate
      - echo "Docker Compose started"
    silent: true

  ##############################################
  # Open Mongosh command in docker
  ##############################################
  mongosh:
    desc: Run a MongoDB shell command in docker
    cmds:
      - docker exec -it mongodb  mongosh
    silent: false

  ##############################################
  # Seed Database
  ##############################################
  seed:
    desc: Seed the database with initial data
    cmds:
      - go run ./cmd/cli/seeddb.go
    silent: false

  # coucou:
  #   desc: Stocke les valeurs passées en ligne de commande (nom et prénom)
  #   cmds:
  #     - |
  #       # Récupérer les arguments
  #       ARGS="{{.CLI_ARGS}}"
  #       # Extraire le premier mot comme nom
  #       NOM=$(echo $ARGS | cut -d' ' -f1)
  #       # Extraire le deuxième mot comme prénom
  #       PRENOM=$(echo $ARGS | cut -d' ' -f2)
  #       # Afficher les résultats
  #       echo "Bonjour $PRENOM $NOM !"
  #       echo "Nom: $NOM"
  #       echo "Prénom: $PRENOM"
  #   silent: false
