version: '3'

tasks:

  help:
    desc: Show help for available tasks
    cmds: 
      - |
        echo "Available tasks:"
        awk '/^  [a-zA-Z_-]+:/ { task = substr($1, 0, length($1)-1); getline; if ($1 == "desc:") { desc = substr($0, 11); printf "  \033[36m%-15s\033[0m %s\n", task, desc } }' taskfile.yml
        echo ""

  server:
    desc: Run the Go server
    cmds:
      - task: proto
      - go run ./cmd/grpcapi/server.go
    silent: false

  clean:
    desc: Clean up the project
    cmds:
      - rm -rf ./proto/gen
    silent: true

  proto:
    desc: Generate Go code from Protobuf files
    cmds:
      - protoc -I=proto --go_out=. --go-grpc_out=. proto/*.proto
      - echo "Protobuf files generated"
    silent: true

  compose:
    desc: Run a Docker Compose command
    cmds:
      - docker compose up -d --force-recreate
      - echo "Docker Compose started"
    silent: true

  mongosh:
    desc: Run a MongoDB shell command
    cmds:
      - docker exec -it mongodb  mongosh
    silent: false

  update:
    desc: Update the project dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
      - echo "Dependencies updated"
    silent: true


  