version: '3'

tasks:

  ##############################################
  # Module support
  ##############################################
  update:
    desc: Update the project dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
      - echo "Dependencies updated"
    silent: true

  ##############################################
  # App support
  ##############################################
  server:
    desc: Run the Go server
    deps:
      - proto
    cmds:
      - go run ./cmd/grpcapi/server.go
      - echo "Server started successfully"  
    silent: false

  clean:
    desc: Clean up the project
    cmds:
      - rm -rf ./proto/gen
    silent: true

  proto:
    desc: Generate Go code from Protobuf files
    cmds:
      - protoc -I=proto --go_out=. --go-grpc_out=. proto/*.proto
      - echo "Protobuf files generated"
    silent: true

  compose:
    desc: Run a Docker Compose command
    cmds:
      - docker compose up -d --force-recreate
      - echo "Docker Compose started"
    silent: true

  mongosh:
    desc: Run a MongoDB shell command in docker
    cmds:
      - docker exec -it mongodb  mongosh
    silent: false
    
  coucou:
    desc: Stocke les valeurs passées en ligne de commande (nom et prénom)
    cmds:
      - |
        # Récupérer les arguments
        ARGS="{{.CLI_ARGS}}"
        # Extraire le premier mot comme nom
        NOM=$(echo $ARGS | cut -d' ' -f1)
        # Extraire le deuxième mot comme prénom
        PRENOM=$(echo $ARGS | cut -d' ' -f2)
        # Afficher les résultats
        echo "Bonjour $PRENOM $NOM !"
        echo "Nom: $NOM"
        echo "Prénom: $PRENOM"
    silent: false

